### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by ArtemKo7v** [ethereumjs/ethereumjs-tx#23]
npm install -g ethereumjs-tx

example.js
```
var Tx = require('ethereumjs-tx')
var privateKey = new Buffer('e331b6d69882b4cb4ea581d88e0b604039a3de5967688d3dcffdd2270c0fd109', 'hex')

var rawTx = {
  nonce: '0x00',
  gasPrice: '0x09184e72a000', 
  gasLimit: '0x2710',
  to: '0x0000000000000000000000000000000000000000', 
  value: '0x00', 
  data: '0x7f7465737432000000000000000000000000000000000000000000000000000000600057'
}

var tx = new Tx(rawTx)
tx.sign(privateKey)

var serializedTx = tx.serialize()
```

nodejs example.js
```
/usr/lib/node_modules/ethereumjs-tx/index.js:194
  Object.assign(this, sig)
         ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at Transaction.sign (/usr/lib/node_modules/ethereumjs-tx/index.js:194:10)
    at Object.<anonymous> (example.js:14:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

```

**Comment by axic** [comment]
ethereumjs-tx depends on ES6 syntax and features. Use nodejs 4 or later or include `es6-shim` in your code.
