### ISSUE TITLE
TypeError: Class constructor Transaction cannot be invoked without 'new' (fake.js:40:26)

### ISSUE THREAD

**Issue by SilentCicero** [ethereumjs/ethereumjs-tx#36]
```
TypeError: Class constructor Transaction cannot be invoked without 'new'
   at new FakeTransaction (/home/nick/github/sol-test/node_modules/ethereumjs-tx/fake.js:40:26)
   at /home/nick/github/sol-test/node_modules/ethereumjs-testrpc/lib/statemanager.js:308:14
   at /home/nick/github/sol-test/node_modules/ethereumjs-testrpc/lib/blockchain_double.js:226:5
   at /home/nick/github/sol-test/node_modules/merkle-patricia-tree/baseTrie.js:76:5
   at /home/nick/github/sol-test/node_modules/merkle-patricia-tree/baseTrie.js:442:14
   at Object.return (/home/nick/github/sol-test/node_modules/merkle-patricia-tree/baseTrie.js:461:9)
   at processNode (/home/nick/github/sol-test/node_modules/merkle-patricia-tree/baseTrie.js:284:30)
   at processNode (/home/nick/github/sol-test/node_modules/merkle-patricia-tree/baseTrie.js:489:5)
   at /home/nick/github/sol-test/node_modules/merkle-patricia-tree/baseTrie.js:485:11
   at /home/nick/github/sol-test/node_modules/merkle-patricia-tree/baseTrie.js:179:7
```

Just started getting this error due from a TestRPC install using `ethereumjs-tx` module. @wanderer can you make this an es2015 sufficient build? Or address this somehow.

Article for reference:
http://stackoverflow.com/questions/30689817/es6-call-class-constructor-without-new-keyword

**Comment by johnmiroki** [comment]
Having the same issue running etherumjs-testrpc. Using `truffle migrate` to send code to testrpc, having the exactly same issue.

**Comment by wanderer** [comment]
I think you can use bable to make es5 builds. I'm not sure how to bundle it though

**Comment by wanderer** [comment]
@kumavis isn't bin-ops make builds or something?

**Comment by wanderer** [comment]
I think this is doing some builds https://github.com/ethereumjs/browser-builds But im not sure how it works
