### ISSUE TITLE
Syntax error in fake.js 

### ISSUE THREAD

**Issue by cgewecke** [ethereumjs/ethereumjs-tx#38]
Getting this error with a freshly installed testrpc on Travis 

_/home/travis/.nvm/versions/node/v5.12.0/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-tx/fake.js:32 module.exports = class FakeTransactiosn extends Transaction { ^^^^^_

*SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode at exports.runInThisContext (vm.js:53:16) at Module._compile (module.js:387:25) at Object.Module._extensions..js (module.js:422:10) at Module.load (module.js:357:32) at Function.Module._load (module.js:314:12) at Module.require (module.js:367:17) at require (internal/module.js:20:19) at Object. (/home/travis/.nvm/versions/node/v5.12.0/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:7:25) at Module._compile (module.js:413:34) at Object.Module._extensions..js (module.js:422:10)*
`

**Comment by cgewecke** [comment]
Closing: 525e002904ebef9d85bdfb2a7843003ee30b976b
