### ISSUE TITLE
Error: Cannot find module 'ethereumjs-tx'

### ISSUE THREAD

**Issue by Tarak-Ram** [ethereumjs/ethereumjs-tx#79]
"IN GETH CONSOLE"

```
> var as = require('ethereumjs-tx')
Error: Cannot find module 'ethereumjs-tx'
    at s (web3.js:1:160)
    at s (web3.js:1:122)
    at <anonymous>:1:10

> 
```

i already installed the module : 
```
root@realeth:/usr/local# npm list | grep ethereumjs
└─┬ ethereumjs-tx@1.3.3
  └─┬ ethereumjs-util@5.1.2
root@realeth:/usr/local# 

```

**Comment by Tarak-Ram** [comment]
Sorry my bad, i figured out that i need to run that in nodejs console not in geth. :D
