### ISSUE TITLE
can't import ethereumjs-tx: TypeError: hex is not a function

### ISSUE THREAD

**Issue by brenzi** [ethereumjs/ethereumjs-tx#82]
npm v3.5.2
node v4.2.6
ubuntu 16.04

installed are:
```
├─┬ ethereumjs-tx@1.3.3 
│ └── ethereumjs-util@5.1.2 
```

test.js:
```
var Tx = require('ethereumjs-tx')
console.log('ok')
```
coinbuntu@coinbuntu:~/ethereum$ node test.js
/home/coinbuntu/node_modules/ethereumjs-tx/node_modules/ethereumjs-util/index.js:31
exports.SHA3_NULL = Buffer.from(exports.SHA3_NULL_S, 'hex')
                           ^

TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
    at Object.<anonymous> (/home/coinbuntu/node_modules/ethereumjs-tx/node_modules/ethereumjs-util/index.js:31:28)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/coinbuntu/node_modules/ethereumjs-tx/es5/index.js:5:15)

```

**Comment by fanatid** [comment]
You need update node version.
`Buffer.from` available only from node 4.6.2 IIRC
