### ISSUE TITLE
Broken Example

### ISSUE THREAD

**Issue by jwasinger** [ethereumjs/ethereumjs-tx#98]
The [code](https://github.com/ethereumjs/ethereumjs-tx/issues/90) gives the following error:

```
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: The field to must have byte length of 20
    at Transaction.setter [as to] (/home/jwasinger/projects/tmp/node_modules/ethereumjs-util/dist/index.js:658:9)
    at /home/jwasinger/projects/tmp/node_modules/ethereumjs-util/dist/index.js:708:63
    at Array.forEach (<anonymous>)
    at Object.exports.defineProperties (/home/jwasinger/projects/tmp/node_modules/ethereumjs-util/dist/index.js:707:14)
    at new Transaction (/home/jwasinger/projects/tmp/node_modules/ethereumjs-tx/es5/index.js:112:13)
    at Object.<anonymous> (/home/jwasinger/projects/tmp/tx.js:16:10)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```

**Comment by holgerd77** [comment]
Adressed in https://github.com/ethereumjs/ethereumjs-tx/pull/107, will close.
